name: work

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y bzip2 python3-pip wget
      - run: pip3 install -r requirements.txt
      - run: ./run.sh
      - uses: actions/upload-artifact@v3
        with:
          name: rib.pkl
          path: rib.pkl

